export const number_input = document.querySelector('#home .feature .number-input')
export const number_input_submit = document.querySelector('#home .feature .number-input-submit')
export const number_input_clear = document.querySelector('#home .feature .number-input-clear')
export const resultBoard = document.querySelector('#home .result')
export const fibonacciResult = document.querySelector('#home .result ul')
export const currentFibonacci = document.querySelector('#home .fibonacci-number span')
export const number_input_form = document.querySelector('#home .feature form')
